export const ActionTypes = {
    ON_LOGIN : 'ON_LOGIN',
    ON_REGISTER : 'ON_REGISTER',
    ON_LOGIN_SUCCESS : 'ON_LOGIN_SUCCESS',
    ON_REGISTER_SUCCESS : 'ON_REGISTER_SUCCESS',
    ON_LOGIN_FAILED : 'ON_LOGIN_FAILED',
    ON_REGISTER_FAILED : 'ON_REGISTER_FAILED',
    ON_LOAD_BOOKS : 'ON_LOAD_BOOKS_SUCCESS',
    ON_LOAD_BOOKS_FAILED : 'ON_LOAD_BOOKS_FAILED',
    ON_LOAD_BOOKS_SUCCESS : 'ON_LOAD_BOOKS_SUCCESS'
}